# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sex',
            field=models.CharField(choices=[('B', '男生'), ('G', '女生'), ('U', '保密')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
