# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='following',
            new_name='follower',
        ),
    ]
