# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cn', models.CharField(max_length=200, null=True)),
                ('image', models.URLField()),
                ('country', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=200)),
                ('duration', models.PositiveSmallIntegerField()),
                ('pubdate', models.DateField()),
                ('year', models.PositiveSmallIntegerField()),
                ('language', models.CharField(max_length=200)),
                ('website', models.URLField(null=True)),
                ('tv', models.CharField(max_length=200, null=True)),
                ('episodes', models.PositiveSmallIntegerField()),
                ('summary', models.TextField(default='')),
                ('num_comments', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('num_raters', models.IntegerField(default=0)),
                ('num_star_one', models.IntegerField(default=0)),
                ('num_star_two', models.IntegerField(default=0)),
                ('num_star_three', models.IntegerField(default=0)),
                ('num_star_four', models.IntegerField(default=0)),
                ('num_star_five', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
