# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meiju', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meiju.Drama')),
            ],
        ),
        migrations.CreateModel(
            name='DramaToType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meiju.Drama')),
            ],
            options={
                'db_table': 'drama_to_type',
            },
        ),
        migrations.CreateModel(
            name='DramaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'drama_type',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meiju.Drama')),
            ],
        ),
        migrations.AddField(
            model_name='dramatotype',
            name='drama_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meiju.DramaType'),
        ),
    ]
