# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meiju', '0003_auto_20170506_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dramatotype',
            name='drama',
        ),
        migrations.RemoveField(
            model_name='dramatotype',
            name='drama_type',
        ),
        migrations.AddField(
            model_name='drama',
            name='types',
            field=models.ManyToManyField(to='meiju.DramaType'),
        ),
        migrations.DeleteModel(
            name='DramaToType',
        ),
    ]
