# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meiju', '0004_auto_20170507_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dramatype',
            name='type',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
