# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meiju', '0005_auto_20170507_1016'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dramatype',
            table='meiju_type',
        ),
    ]
