# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meiju', '0006_auto_20170507_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='title_cn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='tv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
