# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meiju', '0007_auto_20170508_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='drama',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='drama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meiju.Drama'),
        ),
    ]
