# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meiju', '0013_remove_drama_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='website',
        ),
    ]
