# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20170507_0921'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reviewlikes',
            table='reviews_likes',
        ),
    ]
