# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20170507_0922'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reviewcomment',
            table='reviews_comment',
        ),
    ]
