# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20170507_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
