# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20170523_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlikes',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to='reviews.Review'),
        ),
    ]
