# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20170524_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_watched',
            field=models.BooleanField(default=True),
        ),
    ]
