# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_review_is_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pubtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
